### PR TITLE
Add sys/raspberry_pi

### PR DESCRIPTION
**Pull request by fornellas**
Add support for Raspberry Pi using 2 popular libraries to interface with its I/O pins.

### CODE REVIEW

**Comment by fornellas** [comment]
@olikraus out of interest, have you got the chance to review this? I was wondering if it can be merged of if you feel like it requires any changes to it. Tkz.

**Comment by olikraus** [comment]
It does not seem to affect the core lib files, right?
So I could just merge it...

**Comment by fornellas** [comment]
That's correct, just sample code for Raspberry Pi integration.

**Comment by olikraus** [comment]
ups.... merge failed?

**Comment by fornellas** [comment]
Not sure WTH, but it is on master https://github.com/olikraus/ucglib/commits/master, tkz.

**Pull request closed without merging**
